version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: educai
      POSTGRES_PASSWORD: educai_password
      POSTGRES_DB: educai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U educai"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth:
    build: ./auth-service
    environment:
      DATABASE_URL: postgresql://educai:educai_password@db:5432/educai_db
      SECRET_KEY: your_secret_key_here
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  user:
    build: ./user-service
    environment:
      DATABASE_URL: postgresql://educai:educai_password@db:5432/educai_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8005:8005"

  analytics:
    build: ./analytics-service
    environment:
      DATABASE_URL: postgresql://educai:educai_password@db:5432/educai_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

  chatbot:
    build: ./charbot-service
    environment:
      DATABASE_URL: postgresql://educai:educai_password@db:5432/educai_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8002"

  gamification:
    build: ./gamification-service
    environment:
      DATABASE_URL: postgresql://educai:educai_password@db:5432/educai_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8003:8003"

  recommender:
    build: ./recommender-service
    ports:
      - "8004:8004"

  gateway:
    build: ./gateway
    environment:
      AUTH_SERVICE_URL: http://auth:8000
      USER_SERVICE_URL: http://user:8005
      ANALYTICS_SERVICE_URL: http://analytics:8001
      CHATBOT_SERVICE_URL: http://chatbot:8002
      GAMIFICATION_SERVICE_URL: http://gamification:8003
      RECOMMENDER_SERVICE_URL: http://recommender:8004
      SECRET_KEY: your_secret_key_here
      CORS_ORIGINS: "*"
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - user
      - analytics
      - chatbot
      - gamification
      - recommender

volumes:
  postgres_data: