# Generated by Django 5.2.2 on 2025-06-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eleve",
            fields=[
                ("id_eleve", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("levels", models.CharField(max_length=5, null=True)),
                ("matricule_eleve", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="SessionApprentissage",
            fields=[
                ("id_session", models.AutoField(primary_key=True, serialize=False)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Resultat",
            fields=[
                ("id_resultat", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField()),
                ("nb_erreurs", models.IntegerField()),
                ("temps_reponse", models.FloatField()),
                ("date_soumission", models.DateTimeField()),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.eleve"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.sessionapprentissage",
                    ),
                ),
            ],
        ),
    ]
