# Generated by Django 5.2.2 on 2025-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("names", models.TextField()),
                ("email", models.CharField(max_length=30)),
                ("pswd", models.TextField()),
                ("role", models.TextField()),
            ],
        ),
    ]
