# Generated by Django 5.2.2 on 2025-06-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracking.users"
            ),
        ),
        migrations.AlterField(
            model_name="sessionapprentissage",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracking.users"
            ),
        ),
    ]
